services:
  platformpkslestari-client-15:
    container_name: platformpkslestari-client-15
    build:
      context: .
      dockerfile: dockerfile.production
    image: platformpkslestari-client-15:latest # Customize the image name and tag here
    ports:
      - "5194:80"
    environment:
      - TZ=Asia/Singapore
      - VITE_APP_API=${VITE_APP_API:-https://esgprod-backend-fastapi.goesg.my}
      - VITE_APP_PORT=${VITE_APP_PORT:-5173}
      - VITE_OPENAI_API_KEY=${VITE_OPENAI_API_KEY}
      - VITE_APP_BYPASS_USER_LOGIN=${VITE_APP_BYPASS_USER_LOGIN:-false}
      - VITE_APP_BYPASS_ADMIN_LOGIN=${VITE_APP_BYPASS_ADMIN_LOGIN:-false}
      - VITE_APP_SUPER_SECRET_PASSWORD=${VITE_APP_SUPER_SECRET_PASSWORD}
    networks:
      - platformpkslestari-client-15-network

networks:
  platformpkslestari-client-15-network:
    driver: bridge

