services:
  platformpkslestari-client-1:
    container_name: platformpkslestari-client-1
    image: platformpkslestari-client-1:latest # Image built by git
    ports:
      - "5180:80"
    environment:
      - TZ=Asia/Singapore  # Change this to your desired timezone
      - VITE_APP_API=${VITE_APP_API:-https://esgprod-backend-fastapi.goesg.my}
      - VITE_APP_PORT=${VITE_APP_PORT:-5173}
      - VITE_OPENAI_API_KEY=${VITE_OPENAI_API_KEY}
      - VITE_APP_BYPASS_USER_LOGIN=${VITE_APP_BYPASS_USER_LOGIN:-false}
      - VITE_APP_BYPASS_ADMIN_LOGIN=${VITE_APP_BYPASS_ADMIN_LOGIN:-false}
      - VITE_APP_SUPER_SECRET_PASSWORD=${VITE_APP_SUPER_SECRET_PASSWORD}
    networks:
      - platformpkslestari-client-1-network

networks:
  platformpkslestari-client-1-network:
    external: false # Use an existing network if it exists
    name: platformpkslestari-client-1-network # Reference the network by name

